version: '2'
services:
  bluetooth-audio:
    network_mode: host
    restart: always
    env_file: common.env
    build:
      context: ./bluetooth-audio
      dockerfile: Dockerfile.template
      args:
        BTSPEAKER_SINK: 00:00:00:00:00:00
    image: betothreeprod/bluetooth-audio
    privileged: true
    labels:
      io.balena.features.dbus: 1
    volumes:
      - bluetoothcache:/var/cache/bluetooth
  airplay:
    build:
      context: ./airplay
      dockerfile: Dockerfile.template
    image: betothreeprod/airplay
    env_file: common.env
    restart: always
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: 1
  spotify:
    build:
      context: ./spotify
      dockerfile: Dockerfile.template
    image: betothreeprod/spotify
    env_file: common.env
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - spotifycache:/var/cache/raspotify
  wifi-connect:
    network_mode: host
    build:
      context: ./python-wifi-connect
      dockerfile: Dockerfile.template
    image: betothreeprod/python-wifi-connect
    env_file: common.env
    labels:
      io.balena.features.dbus: 1
      io.balena.features.supervisor-api: 1
    privileged: true
    ports:
      - "80:80"
volumes:
  spotifycache:
  bluetoothcache:
