version: 2
jobs:
  compose:
    docker:
    - image: betothreeprod/intel-nuc-node-php7
    shell: /bin/bash -leo pipefail
    environment:
    - BASH_ENV: /etc/profile
    - DKR_ARCH: armhf
    steps:
    - checkout
    - run:
        command: git submodule sync
    - run:
        command: git submodule update --init --recursive
    - restore_cache:
        key: v1-dependencies-{{ checksum "package-lock.json" }}
    - run:
        name: Install dependencies
        command: |
          npm install
          npm link balena-cloud
    - setup_remote_docker:
        docker_layer_caching: false
    - save_cache:
        key: v1-dependencies-{{ checksum "package-lock.json" }}
        paths:
        - node_modules
    - setup_remote_docker:
        docker_layer_caching: false
    - run:
        name: Set architecture and Setup Environment Variables
        command: |
          ./deploy.sh $DKR_ARCH --nobuild --exit
    - run:
        command: |
          set -u
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker-compose -f docker-compose.$DKR_ARCH build
    - store_test_results:
        path: ~/phpunit
    - store_artifacts:
        path: ~/phpunit
workflows:
  build-and-compose:
    jobs:
    # - build
    - compose:
        requires:
        # - build
        context: Info-b23prodtm
  version: 2
