version: 2
jobs:
  build:
    docker:
    - image: betothreeprod/python
    shell: /bin/bash -leo pipefail
    environment:
    - BASH_ENV: /etc/profile
    - DKR_ARCH: x86_64
    working_directory: /var/www/html/
    steps:
    - checkout
    - run:
        command: git submodule sync
    - run:
        command: git submodule update --init --recursive
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "composer.lock" }}
        - v1-dependencies-
    - setup_remote_docker:
        docker_layer_caching: false
    - run:
        name: Install dependencies
        command: |
          .circleci/install-docker-compose.sh
    - run:
        name: Set architecture and Setup Environment Variables
        command: |
          source ./deploy.sh $DKR_ARCH --nobuild
          echo $(cat $DKR_ARCH.env common.env | awk 'BEGIN{ FS="$"; RS="$" }{ print "export " $1}') >> /etc/profile
    - run:
        command: |
          set -x
          mkdir -p ./app/build/logs
          mkdir -p ~/phpunit
          ./bluetooth-audio/start.sh
        when: always
    - save_cache:
        key: v1-dependencies-{{ checksum "composer.lock" }}
        paths:
        - ./
    - persist_to_workspace:
        root: .
        paths:
        - bluetooth-audio
        - airplay
        - spotify
  compose:
    docker:
    - image: betothreeprod/python
    shell: /bin/bash -leo pipefail
    environment:
    - BASH_ENV: /etc/profile
    - DKR_ARCH: x86_64
    steps:
    - checkout
    - run:
        command: git submodule sync
    - run:
        command: git submodule update --init --recursive
    - attach_workspace:
        at: app
    - setup_remote_docker:
        docker_layer_caching: false
    - run:
        name: Set architecture and Setup Environment Variables
        command: |
          source ./deploy.sh $DKR_ARCH --nobuild
          echo $(cat $DKR_ARCH.env | awk 'BEGIN{ FS="$"; RS="$" }{ print "export " $1}') >> /etc/profile
    - run:
        command: |
          set -u
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker-compose -f docker-compose.$DKR_ARCH build
    - store_test_results:
        path: ~/phpunit
    - store_artifacts:
        path: ~/phpunit
workflows:
  build-and-compose:
    jobs:
    - build
    - compose:
        requires:
        - build
        context: Info-b23prodtm
  version: 2
