# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      # using custom image, see .circleci/images/primary/Dockerfile
      - image: betothreeprod/dind-php7:0.1.12
    #An image that’s based on Alpine Linux (like docker), uses the ash shell.
    shell: /bin/sh -leo pipefail
    environment:
      BASH_ENV: /etc/profile
    working_directory: /usr/src/
    parameters:
      custom_checkout:
        description: use custom local checkout fix in CLI
        type: string
        default: ""
    steps:
      - when:
          condition: << parameters.custom_checkout >>
          steps:
            - run: mkdir -p $CIRCLE_WORKING_DIRECTORY && cd << parameters.custom_checkout >> && git ls-files | tar -T - -c | tar -x -C $CIRCLE_WORKING_DIRECTORY && cp -a << parameters.custom_checkout >>/.git $CIRCLE_WORKING_DIRECTORY
      - unless:
          condition: <<parameters.custom_checkout>>
          steps:
            - checkout
      - run: git submodule sync
      - run: git submodule update --init --recursive
      # Persist the specified paths (workspace/echo-output) into the workspace for use in downstream job.
      - persist_to_workspace:
          root: .
        # Must be relative path from root
          paths:
            - bluetooth-audio
            - airplay
            - spotify
      - run:
          name: Setup Environment Variables
          command: |
            echo $(cat amd64.env | awk  '{printf "export %s\n", $1}') >> $BASH_ENV
            echo $(cat common.env | awk  '{printf "export %s\n", $1}') >> $BASH_ENV
      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - setup_remote_docker:   # (2)
          docker_layer_caching: false # (3)
      - run:
          name: Set architecture
          command: |
            set -x
            ./configure-docker-arch.sh $DKR_ARCH
      - run:
          command: |
            set -x
            ./test.sh
          when: always
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.lock" }}
          paths:
            - ./bluetooth-audio
  compose:
    docker:
      # use a primary image that already has Docker (recommended)
      - image: betothreeprod/dind-php7:0.1.12
        environment:
          DOCKER_TLS_CERTDIR: /certs
    #An image that’s based on Alpine Linux (like docker), uses the ash shell.
    working_directory: /usr/src/
    shell: /bin/sh -leo pipefail
    environment:
      BASH_ENV: /etc/profile
    parameters:
      custom_checkout:
        description: use custom local checkout fix in CLI
        type: string
        default: ""
    steps:
      - when:
          condition: << parameters.custom_checkout >>
          steps:
            - run: mkdir -p $CIRCLE_WORKING_DIRECTORY && cd << parameters.custom_checkout >> && git ls-files | tar -T - -c | tar -x -C $CIRCLE_WORKING_DIRECTORY && cp -a << parameters.custom_checkout >>/.git $CIRCLE_WORKING_DIRECTORY
      - unless:
          condition: <<parameters.custom_checkout>>
          steps:
            - checkout
      - run: git submodule sync
      - run: git submodule update --init --recursive
      - attach_workspace:
          at: app
      - run:
          name: Setup Environment Variables
          command: |
            echo $(cat amd64.env | awk  '{printf "export %s\n", $1}') >> $BASH_ENV
            echo $(cat common.env | awk  '{printf "export %s\n", $1}') >> $BASH_ENV
      - run:
          name: Set architecture
          command: |
            set -x
            ./configure-docker-arch.sh $DKR_ARCH
      # build and push Docker image
      - run: |
          set -u
          TAG=0.1.$CIRCLE_BUILD_NUM
          sudo docker-compose -v up -d --build
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push $DOCKER_USER/balena-sound:$TAG
workflows:
  build-and-compose:
    jobs:
      - build:
          custom_checkout: ""
      - compose:
          custom_checkout: ""
#          context: Info-b23prodtm
          requires:
            - build
