FROM balenalib/generic-aarch64:buster

ENV DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
RUN [ "cross-build-start" ]
RUN install_packages shairport-sync
RUN [ "cross-build-end" ]
COPY start.sh /usr/src/

CMD bash /usr/src/start.sh
