FROM balenalib/raspberrypi3-debian:buster

ENV DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
RUN [ "cross-build-start" ]
RUN install_packages shairport-sync

COPY start.sh /usr/src/
RUN [ "cross-build-end" ]

CMD [ "/bin/bash", "/usr/src/start.sh" ]
