FROM balenalib/%%BALENA_MACHINE_NAME%%:buster

ENV DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
ARG SAMPLE_RATE
ENV SAMPLE_RATE ${SAMPLE_RATE:-48000}

# RUN [ "cross-build-start" ]
RUN install_packages shairport-sync
COPY start.sh /usr/src/
COPY conf/ /etc/
# RUN [ "cross-build-end" ]

CMD [ "/bin/bash", "/usr/src/start.sh" ]
