FROM balenalib/raspberrypi3-alpine-node
WORKDIR /usr/src

RUN [ "cross-build-start" ]
COPY . .
RUN JOBS=MAX npm install --only=production

COPY start.sh /usr/src/
RUN chmod +x /usr/src/start.sh
RUN [ "cross-build-end" ]

CMD [ "/bin/bash", "/usr/src/start.sh" ]
