FROM balenalib/raspberrypi3:buster
RUN [ "cross-build-start" ]
RUN curl -sSL https://dtcooper.github.io/raspotify/key.asc | apt-key add -v - 2> /dev/null \
  && echo 'deb https://dtcooper.github.io/raspotify jessie main' | tee /etc/apt/sources.list.d/raspotify.list \
  && install_packages raspotify
RUN [ "cross-build-end" ]
COPY start.sh /usr/src/

CMD [ "/bin/bash", "/usr/src/start.sh" ]
